apiVersion: apps/v1
kind: Deployment
metadata:
  name: research-cruise-app-frontend
spec:
  template:
    spec:
      containers:
        - name: research-cruise-app-frontend
          volumeMounts:
            - name: nginx-snippets
              mountPath: /etc/nginx/conf.d/rybbit-subfilter.conf
              subPath: rybbit-subfilter.conf
      volumes:
        - name: nginx-snippets
          configMap:
            name: nginx-snippets
